---
title: "Drosophila melanogaster - TE invasions origin"
output: rmarkdown::github_document
editor_options: 
  markdown: 
    wrap: sentence
    author: Riccardo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(svglite))
theme_set(theme_bw())
```

```
for i in *.ori.out; do cat $i| python ../reader-rm.py| python ../rm-cleanup.py > $i.clean; done

for i in *ori.out.clean; do awk '{print $0,FILENAME}' $i |perl -pe 's/\.fa\.ori\.out\.clean//'; done > merged.clean.sum

python score-max.py --rm merged.clean.sum > merged.clean.score
```

```{r}
sortorder<-c("D.flavopinicola","D.maculinotata","S.hsui","S.polygonia","S.montana","S.graminum","S.caliginosa","S.parva","S.pallida","S.reducta","S.tumidula","S.cyrtandrae","D.setosimentum","D.quasianomalipes","D.anomalipes","D.cyrtoloma","D.melanocephala","D.differens","D.planitibia","D.silvestris","D.heteroneura","D.picticornis","D.basisetae","D.paucipuncta","D.glabriapex","D.macrothrix","D.hawaiiensis","D.crucigera","D.pullipes","D.grimshawi","D.engyochracea","D.villosipedis","D.ochracea","D.murphyi","D.sproati","D.dives","D.multiciliata","D.demipolita","D.longiperda","D.melanosoma","D.fungiperda","D.mimica","D.infuscata","D.kambysellisi","D.cognata","D.tanythrix","D.yooni","D.kokeensis","D.nrfundita","D.cracens","D.paracracens","D.nigritarsus","D.nrmedialis2","D.nrmedialis3","D.seclusa","D.nrperissopoda1","D.nrperissopoda5","D.atroscutellata","D.imparisetae","D.trichaetosa","D.percnosoma","D.neutralis","D.incognita","D.sordidapex","D.conformis","D.paramelanica","D.colorata","D.robusta","D.sordidula","D.borealis","D.montana","D.lacicola","D.americana","D.virilis","D.littoralis","D.ezoana","D.kanekoi","D.pseudotalamancana","D.gaucha","D.mettleri","D.eohydei","D.pegasa","D.nigricruria","D.fulvimacula","D.peninsularis","D.paranaensis","D.repleta","D.mercatorum","D.leonis","D.anceps","D.meridiana","D.meridionalis","D.stalkeri","D.buzzatii","D.hamatofila","D.mayaguana","D.mojavensis","D.aldrichi","D.mulleri","Z.flavofinira","H.trivittata","H.alboralis","H.confusa","H.histrioides","D.repletoides","H.guttata","L.aerea","Z.bogoriensis","Z.ghesquierei","Z.inermis","Z.kolodkinae","Z.tsacasi.jd01t","Z.tsacasi.car7","Z.ornatus","Z.africanus","Z.indianus.bs02","Z.indianus.d18","Z.gabonicus","Z.indianus.r04","Z.indianus.v01","Z.capensis","Z.taronus","Z.davidi","Z.camerounensis","Z.nigranus","Z.lachaisei","Z.vittiger","D.quadrilineata","D.pruinosa","D.niveifrons","D.rubida","D.siamana","D.immigrans.12","D.immigrans.k17","D.ustulata","D.formosana","D.tripunctata","D.cardini","D.parthenogenetica","D.acutilabella","D.arawakana","D.dunni","D.macrospina","D.funebris","D.putrida","D.neotestacea","D.testacea","D.histrio","D.kuntzei","D.sp.st01m","D.phalerata","D.falleni","D.rellima","D.quinaria","D.suboccidentalis","D.recens","D.subquinaria","S.latifasciaeformis","C.caudatula","C.procnemis","C.amoena","C.costata","S.nigrithorax","L.varia","L.montana","L.maculata","C.indagator","A.minor","A.mariae","A.communis","H.duncani","L.mommai","L.collinella","L.andalusiaca","L.magnipectinata","L.clarofinis","L.stackelbergi","D.sturtevanti","D.neocordata","D.emarginata","D.saltans","D.prosaltans","D.austrosaltans","D.sucinea","D.sp.14030-0761.01","D.insularis","D.tropicalis","D.willistoni.00","D.willistoni.17","D.equinoxialis","D.paulistorum.12","D.paulistorum.06","D.subobscura","D.subsilvestris","D.obscura","D.ambigua","D.tristis","D.miranda","D.persimilis","D.pseudoobscura","D.helvetica","D.algonquin","D.affinis","D.varians","D.vallismaia","D.merina","D.ercepeae","D.atripex","D.monieri","D.anomalata","D.ananassae","D.pallidosa","D.pseuan.pseuan.","D.pseuan.nigrens","D.mal.mal.","D.mal.pallens","D.parabipectinata","D.bipectinata","D.rufa","D.triauraria","D.kikkawai","D.jambulina","D.aff.chauv.","D.bocqueti","D.birchii","D.anomelani","D.serrata","D.bunnanda","D.oshimai","D.gunungcola","D.elegans","D.fuyamai","D.kurseongensis","D.rhopaloa","D.carrolli","D.ficusphila","D.biarmipes","D.subpulchrella","D.mimetica","D.lutescens","D.takahashii","D.pseudotakahashii","D.prostipennis","D.eugracilis","D.erecta","D.yakuba","D.teissieri.273.3","D.teissieri.ct02","D.mel.ral732","D.mel.ral737","D.mel.pi2","D.mel.ral176","D.mel.ral91","D.mel.se.sto","D.mel.es.ten","D.mel.TOM008","D.melanogaster","D.mel.iso1","D.sechellia","D.sim.006","D.sim.sz232","D.sim.sz129","D.mau.01","D.mau.r31","D.mau.r61","D.mau.r32","D.mau.r39")

teorder<-c("Blood", "Opus", "412", "Tirant", "I-element", "Hobo", "P-element", "Spoink", "Micropia", "Souslik", "Transib1")

grouporder<-c("D.melanogaster", "D.simulans", "D.mauritiana", "D.sechellia", "D.melanogaster group", "D.willistoni group", "D.saltans group", "D.cardini group", "Zaprionus", "D.repleta group", "other drosophilids", "no TE")
```

```{r}
h <- read_tsv("/Volumes/Storage/dmel-full-story/RepeatMasker/output/merged.clean.score", col_names = c("te", "species", "similarity")) %>% filter(te!="Shellder") %>% mutate(te = case_when(te=="Transib_Riccardo" ~ "Transib1", te=="PPI251" ~ "P-element", te=="DMIFACA" ~ "I-element", TRUE ~ te))
h$species <- factor(h$species, levels=sortorder)
h$te <- factor(h$te, levels=teorder)

colorcode <- read_tsv("/Volumes/Storage/dmel-full-story/TE-trees/color-code-R-groups.txt")
colorcode$group <- factor(colorcode$group, levels=grouporder)

colorcode <- colorcode %>% arrange(group)
colors <- colorcode %>% select(RGB) %>% distinct() %>% pull()

h_color <- h %>%
  mutate(species_unique = species, species = case_when(
    grepl("^D\\.mau", species) ~ "D.mauritiana",
    grepl("^D\\.sim", species) ~ "D.simulans",
    species %in% c("D.mel.ral732","D.mel.ral737","D.mel.pi2","D.mel.ral176","D.mel.ral91","D.mel.se.sto","D.mel.es.ten","D.mel.TOM008","D.melanogaster","D.mel.iso1") ~ "D.melanogaster",
    grepl("^D\\.will", species) ~ "D.willistoni",
    grepl("^D\\.teis", species) ~ "D.teissieri",
    grepl("^D\\.pauli", species) ~ "D.paulistorum",
    grepl("^Z\\.ind", species) ~ "Z.indianus",
    TRUE ~ species)) %>%
    left_join(colorcode, by="species") %>% 
    mutate(final_group = ifelse(is.na(group), "no TE", as.character(group)), group = as.factor(final_group), ancestry = ifelse(te %in% c("P-element", "Spoink", "Micropia"), "American drosophilids", "African drosophilids"))

h_color$species <- factor(h_color$species, levels=sortorder)
h_color$te <- factor(h_color$te, levels=teorder)
h_color$group <- factor(h_color$group, levels=grouporder)

h_color
```

```{r}
(p <- ggplot(h_color,aes(y=similarity, x=species_unique, fill=group))+
  geom_bar(stat="identity")+
  facet_grid(te~.)+
  labs(y="similarity", fill="species")+
  scale_fill_manual(values = colors)+
  theme(axis.title.x=element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank(), legend.key.width = unit(0.1, "in"),  # Adjust the width of legend keys
          legend.key.height = unit(0.25, "in"), # Adjust the height of legend keys
          legend.spacing.x = unit(0.1, "in"), # Adjust horizontal spacing between legend elements
          legend.spacing.y = unit(0.1, "in"), # Adjust vertical spacing between legend elements
          legend.margin = margin(0, 0, 0, 0))+
    guides(fill = guide_legend(ncol = 1))+
    theme(panel.grid.major = element_blank(),  # Remove major grid lines
        panel.grid.minor = element_blank()))

#pdf(file="/Volumes/Storage/dmel-full-story/RepeatMasker/dmel-full-story-origin.pdf",width=7,height=12)
#plot(p)
#dev.off()

ggsave("/Volumes/Storage/dmel-full-story/figures/origin.png",p,width=7,height=9)
```

```{r}
(p_color <- ggplot(h_color,aes(y=similarity, x=species_unique, fill=group))+
  geom_bar(stat="identity")+
  facet_grid(te~.)+
  labs(y="similarity", fill="species", colour="TE origin")+
  scale_fill_manual(values = colors)+
   scale_color_manual(values = c("brown1", "palegreen")) +
  theme(axis.title.x=element_blank(), axis.text.x = element_blank(), axis.ticks.x = element_blank(), legend.key.width = unit(0.1, "in"),  # Adjust the width of legend keys
          legend.key.height = unit(0.25, "in"), # Adjust the height of legend keys
          legend.spacing.x = unit(0.1, "in"), # Adjust horizontal spacing between legend elements
          legend.spacing.y = unit(0.1, "in"), # Adjust vertical spacing between legend elements
          legend.margin = margin(0, 0, 0, 0))+
    guides(fill = guide_legend(ncol = 1))+
    theme(panel.grid.major = element_blank(),  # Remove major grid lines
        panel.grid.minor = element_blank())+
   geom_rect(data = h_color,aes(color = ancestry, fill=NA), size=2, xmin = -Inf, xmax = Inf,
            ymin = -Inf, ymax = Inf, alpha = 0))

#ggsave("/Volumes/Storage/dmel-full-story/figures/origin-region.png",p_color,width=7,height=9)
```

```{r}
(p<- ggplot(h,aes(x=similarity,y=species))+geom_bar(stat="identity")+facet_grid(.~te)+xlab("similarity")+
  theme(axis.title.y=element_blank(),axis.text.y = element_text(vjust = 0.5, hjust=1,size=4)))

#pdf(file="/Volumes/Storage/dmel-full-story/RepeatMasker/dmel-full-story-origin-vertical.pdf",width=12,height=12)
#plot(p)
#dev.off()

#ggsave("/Volumes/Storage/dmel-full-story/RepeatMasker/dmel-full-story-origin-vertical.png",p,width=7,height=12)
```

```{r}
h %>% filter(te=="Micropia") %>% arrange(desc(similarity))

(tom008 <- read_tsv("/Volumes/Storage/dmel-full-story/RepeatMasker/output/D.mel.TOM008.fa.ori.out.clean", col_names = c("rm","SW","pid","contig","qstart","qend","strand","te","rstart","rend","score","strain")) %>% filter(te=="Micropia") %>% arrange(desc(SW)))

(ral176 <- read_tsv("/Volumes/Storage/dmel-full-story/RepeatMasker/output/D.mel.ral176.fa.ori.out.clean", col_names = c("rm","SW","pid","contig","qstart","qend","strand","te","rstart","rend","score","strain")) %>% filter(te=="Micropia") %>% arrange(desc(SW)))
```


## Anastrepha

(Anastrepha)
```{r}
#h_shell <- read_tsv("/Volumes/Storage/dmel-full-story/RepeatMasker/output+anastrepha/merged.clean.score", col_names = #c("te", "species", "similarity"))

#sortorder_shell<-c("A.ludens","A.obliqua","D.eohydei","D.pegasa","D.nigricruria","D.fulvimacula","D.peninsularis","D.paranaensis","D.repleta","D.mercatorum","D.leonis","D.anceps","D.meridiana","D.meridionalis","D.cardini","D.parthenogenetica","D.acutilabella","D.arawakana","D.dunni","D.macrospina","D.funebris","D.putrida","D.neotestacea","D.testacea","D.histrio","D.kuntzei","D.sp.st01m","D.phalerata","D.falleni","D.rellima","D.quinaria","D.suboccidentalis","D.recens","D.subquinaria","D.sp.14030-0761.01","D.insularis","D.tropicalis","D.willistoni.00","D.willistoni.17","D.equinoxialis","D.paulistorum.12","D.paulistorum.06","D.subobscura","D.subsilvestris","D.obscura","D.ambigua","D.tristis","D.miranda","D.persimilis","D.pseudoobscura","D.helvetica","D.algonquin","D.affinis","D.varians","D.vallismaia","D.merina","D.ercepeae","D.atripex","D.monieri","D.anomalata","D.ananassae","D.eugracilis","D.erecta","D.yakuba","D.teissieri.273.3","D.teissieri.ct02","D.mel.ral732","D.mel.ral737","D.mel.pi2","D.mel.ral176","D.mel.ral91","D.mel.se.sto","D.mel.es.ten","D.melanogaster","D.mel.iso1","D.sechellia","D.sim.006","D.sim.sz232","D.sim.sz129","D.mau.01","D.mau.r31","D.mau.r61","D.mau.r32","D.mau.r39")

#h_shell$species <- factor(h_shell$species, levels=sortorder_shell)
#h_shell$te <- factor(h_shell$te, levels=teorder)

#add <- c("A.ludens.fna.ori.out.clean","A.obliqua.fna.ori.out.clean")

#(h_shell_filter <- h_shell %>% filter(te=="Shellder", species %in% sortorder_shell))

#(p_shell <- ggplot(h_shell_filter,aes(y=similarity,x=species))+
#  geom_bar(stat="identity")+
#  facet_grid(te~.)+
#  ylab("similarity")+
#  theme(axis.title.x = element_blank(),
#        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)))
```
