---
title: "Drosophila melanogaster - TE invasions timing"
output: rmarkdown::github_document
editor_options: 
  markdown: 
    wrap: sentence
    author: Riccardo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(svglite))
theme_set(theme_bw())
```

## File import

Read metadata and copynumber estimates
```{r}
invaders <- read_tsv("/Volumes/Storage/dmel-full-story/dataset.tsv", show_col_types = FALSE) %>% mutate(presence = ifelse(HQ_reads>=2.5, "present", "absent")) %>% filter(!(Sample %in% c("SRR8061818", "SRR8061819")))

HT_estimates <- tibble(
  TE = c("Blood", "Opus", "412", "Tirant", "I-element", "Hobo", "P-element", "Spoink", "Micropia", "Souslik", "Transib1"),
  HT = c(1900, 1900, 1900, 1935, 1950, 1960, 1965, 1985, 1985, 2005, 2010))

(invaders_meta <- inner_join(invaders, HT_estimates, by="TE") %>% mutate(new_alleles = ifelse(reinvasion==TRUE, new_alleles, ifelse(HQ_reads > 1, 1, 0))))
  
invaders_meta$TE <- factor(invaders_meta$TE, levels = c("Blood", "Opus", "412", "Tirant", "I-element", "Hobo", "P-element", "Spoink", "Micropia", "Souslik", "Transib1"))
```

## Timeline

Plot copynumbers in timelines.
```{r}
invading <- invaders_meta %>% filter(reinvasion==FALSE)

timeline_invading <- ggplot(invading, aes(x=year, y=HQ_reads, color=presence)) + geom_point(alpha=0.5, size=5) +
    labs(y = "copynumber", x = "") +
    scale_x_continuous(breaks = seq(1800, max(invaders_meta$year), by = 10), labels = seq(1800, max(invaders_meta$year), by = 10))+
    scale_color_manual(values=c("darkgreen","red"))+
    facet_grid(TE ~ .)+
    #geom_vline(xintercept = timeline$HT, 
    #         linetype = "dashed", color = "red") +
    theme(legend.position = "top", 
        axis.text.x = element_text(angle = 45, hjust = 1))

reinvading <- invaders_meta %>% filter(reinvasion==TRUE)

timeline_reinvading <- ggplot(reinvading, aes(x=year, y=new_alleles, color=new_alleles)) + geom_point(alpha=0.5, size=5) +
    labs(y = "new alleles frequency", x = "") +
    scale_x_continuous(breaks = seq(1800, max(invaders_meta$year), by = 10), labels = seq(1800, max(invaders_meta$year), by = 10))+
    scale_color_gradient(low="darkgreen",high="red")+
    facet_grid(TE ~ .)+
    #geom_vline(xintercept = timeline$HT, 
    #         linetype = "dashed", color = "red") +
    theme(legend.position = "none", 
        axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
(timeline_combined <- ggplot(invaders_meta, aes(x=year, y=HQ_reads, color=new_alleles)) + geom_point(alpha=0.5, size=3) +
    labs(y = "copynumber", x = "", color = "new alleles frequencies") +
    scale_x_continuous(breaks = seq(1800, max(invaders_meta$year), by = 10), labels = seq(1800, max(invaders_meta$year), by = 10))+
    scale_color_gradient(low="darkgreen",high="red")+
    facet_grid(TE ~ ., scales = "free_y")+
    #geom_vline(xintercept = timeline$HT, 
    #         linetype = "dashed", color = "red") +
    theme(legend.position = "top", 
        axis.text.x = element_text(angle = 45, hjust = 1)))

ggsave("/Volumes/Storage/dmel-full-story/figures/shortreads.png", plot = timeline_combined, height = 12)
```