---
title: "Drosophila melanogaster - TE invasions timing - outliers"
output: rmarkdown::github_document
editor_options: 
  markdown: 
    wrap: sentence
    author: Riccardo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(svglite))
theme_set(theme_bw())
```

## File import

Read metadata and copynumber estimates
```{r}
(invaders <- read_tsv("/Volumes/Storage/dmel-full-story/dataset.tsv", show_col_types = FALSE) %>% mutate(presence = ifelse(HQ_reads>=2.5, "present", "absent")))

HT_estimates <- tibble(
  TE = c("Blood", "Opus", "412", "Tirant", "I-element", "Hobo", "P-element", "Spoink", "Micropia", "Souslik", "Transib1"),
  HT = c(1900, 1900, 1900, 1935, 1950, 1960, 1965, 1985, 1985, 2005, 2010))

invaders_meta <- inner_join(invaders, HT_estimates, by="TE")
  
invaders_meta$TE <- factor(invaders_meta$TE, levels = c("Blood", "Opus", "412", "Tirant", "I-element", "Hobo", "P-element", "Spoink", "Micropia", "Souslik", "Transib1"))
```

## Outliers extraction

```{r}
outliers_detection_snps <- invaders_meta %>% filter(reinvasion==TRUE, new_alleles<0.3, year>1960, TE!="Transib1", TE!="Souslik") %>% arrange(year)

outliers_detection_cn <- invaders_meta %>% filter(reinvasion==FALSE, HQ_reads<2.5, year>1995, TE!="Transib1", TE!="Souslik") %>% arrange(year)

(outliers <- invaders_meta %>% filter(Sample %in% c("SRR23876563", "SRR8494428", "SRR189075", "SRR189073", "SRR8061818", "SRR8061819")))
outliers$Sample <- factor(outliers$Sample, levels = c("SRR23876563", "SRR8494428", "SRR189075", "SRR189073", "SRR8061818", "SRR8061819"))

(outliers_p <- ggplot(outliers, aes(x=TE, y=HQ_reads, fill=new_alleles))+
  geom_bar(stat="identity")+
    scale_fill_gradient(low="darkgreen", high = "red")+
  facet_wrap(~Sample, ncol = 1)+
    labs(x="", y="copynumber", fill = "new alleles frequency")+
    theme(legend.position = "top"))

ggsave("/Volumes/Storage/dmel-full-story/figures/outliers.png", plot = outliers_p, height = 12)
```




